# Resume this session with:
# claude --resume 66217177-a0fe-40c3-a9ce-ba1b75021203

# --- Imports ---
import os
import sys
import time
import struct
import threading
import ok          # OpalKelly FrontPanel API - communication with the FPGA (USB)

# --- Project paths ---
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
# Bitstream file generated by Vivado, loaded onto the FPGA
# BIT_FILE = os.path.join(REPO_ROOT, "HW", "vivado", "kws", "kws_system.runs", "impl_1", "ok_top_wrapper.bit")
BIT_FILE = r"bitstreams/ok_top_wrapper_newest.bit"

# List of words recognized by the model - order matches the class indices returned by the FPGA
WORDS_COMM = [
    "up", "down", "left", "right", "one", "two", "unknown", "None", "None", "None", "None"
]

# --- Continuous mode parameters ---
BYTES_PER_FRAME = 16               # size of a single frame (4x uint32)
CONFIDENCE_THRESHOLD = 179         # confidence threshold (0-255), below which a frame is rejected as unreliable
NUM_FRAMES = 100                   # Read from FIFO each time
DEBUG = False                       # per-batch diagnostics (fifo_cnt, number of high-confidence frames)

# --- Initialize the connection to the FPGA via FrontPanel ---
devices = ok.FrontPanelDevices()
dev = devices.Open("")     # opens the first detected OpalKelly device

if dev is None:
    print("Device could not be opened")
    sys.exit(1)

dp = None


def configure_fpga():
    # Load the bitstream (FPGA configuration) - after this step the chip starts operating per the synthesized design.
    # The data port handle is re-acquired after every configuration.
    global dp
    cfg_result = dev.ConfigureFPGA(BIT_FILE)
    if cfg_result != 0:
        print(f"FPGA configuration failed, error code {cfg_result}")
        sys.exit(1)

    # Let the device settle after reprogramming before touching its endpoints
    # (same as in demo.py - WireIn too soon after reprogramming can break FrontPanel)
    time.sleep(0.3)

    # Handle to the FrontPanel data port - used to control WireIn/WireOut and read PipeOut
    dp = dev.GetFPGADataPortClassic()
    if dp is None:
        print("Failed to get FPGA Data Port.")
        sys.exit(1)


configure_fpga()
print("FPGA configured successfully.")
print(dp)

def reset_pipeline():
    # Reset pulse on WireIn 0x00 (bit0: 0 -> 1 -> 0) - zeroes the inference pipeline on the FPGA
    dp.SetWireInValue(0x00, 1, 1)
    dp.UpdateWireIns()
    time.sleep(0.01)
    dp.SetWireInValue(0x00, 0, 1)
    dp.UpdateWireIns()
    time.sleep(0.01)


def arm_pipeline():
    # Set WireIn 0x01 (bit0 = 1) - arms the pipeline. In continuous mode this stays
    # set once at startup and remains active - audio is fed continuously by the microphone
    # connected directly to the ADC input, there's no .wav file playback
    dp.SetWireInValue(0x01, 1, 1)
    dp.UpdateWireIns()
    time.sleep(0.01)


def disarm_pipeline():
    # Disarm (bit0 = 0) - called once, when the program shuts down
    dp.SetWireInValue(0x01, 0, 1)
    dp.UpdateWireIns()
    time.sleep(0.01)


def reload_and_reset():
    # Full restart after a detection: reload the bitstream, reset and re-arm the pipeline
    print("[RESET] Reloading bitstream...")
    t0 = time.time()
    disarm_pipeline()
    configure_fpga()
    print(f"[RESET] Bitstream loaded ({time.time() - t0:.2f} s)")
    reset_pipeline()
    arm_pipeline()
    dp.UpdateWireOuts()
    print(f"[RESET] Pipeline reset and armed, fifo_cnt={dp.GetWireOutValue(0x20)} "
          f"({time.time() - t0:.2f} s) - listening again")


def read_frame_batch(no_frames):
    # Read one batch of no_frames frames from PipeOut 0xA0
    read_size = no_frames * BYTES_PER_FRAME
    buf = bytearray(read_size)
    dp.ReadFromPipeOut(0xA0, buf)

    captured_frames = []

    # Decode the raw bytes frame by frame (same format as in kws_PWZ.py)
    for i in range(0, read_size, BYTES_PER_FRAME):
        chunk = buf[i:i + BYTES_PER_FRAME]
        word1, word2, word3, word4 = struct.unpack('<IIII', chunk)

        # An all-zero frame = no new data - skip it
        if word1 == 0 and word2 == 0 and word3 == 0 and word4 == 0:
            continue

        # The lowest byte of word4 is the confidence level of this frame's classification result
        confidence = word4 & 0xFF

        # The remaining bytes (11 x 8-bit result) are the raw scores for the 11 WORDS_COMM classes,
        # packed sequentially into word4 (upper bytes), word3, word2
        class_scores = [
            (word4 >> 8) & 0xFF,
            (word4 >> 16) & 0xFF,
            (word4 >> 24) & 0xFF,
            word3 & 0xFF,
            (word3 >> 8) & 0xFF,
            (word3 >> 16) & 0xFF,
            (word3 >> 24) & 0xFF,
            word2 & 0xFF,
            (word2 >> 8) & 0xFF,
            (word2 >> 16) & 0xFF,
            (word2 >> 24) & 0xFF
        ]

        # the first four are subtracted 125 meanwhile the rest is ignored
        class_scores[0] = class_scores[0] - 125
        class_scores[1] = class_scores[1] - 125
        class_scores[2] = class_scores[2] - 125
        class_scores[3] = class_scores[3] - 125
        class_scores[4] = -128
        class_scores[5] = -128
        class_scores[6] = class_scores[6] - 185
        class_scores[7] = -128
        class_scores[8] = -128
        class_scores[9] = -128
        class_scores[10] = -128
#        print(str(class_scores) + " | " + str(confidence))

        captured_frames.append({
            "confidence": confidence,
            "scores": class_scores
        })
        #print(class_scores)
    return captured_frames


def classify_batch(frames, confidence_threshold=CONFIDENCE_THRESHOLD):
    # Filter out low-confidence frames - only "reliable" frames count toward the result
    high_conf_frames = [f for f in frames if f["confidence"] > confidence_threshold]

    if len(high_conf_frames) == 0:
        return None

    # Average the scores over all reliable frames for each of the 11 classes
    avg_scores = [0] * 11
    for frame in high_conf_frames:
        for class_idx in range(11):
            avg_scores[class_idx] += frame["scores"][class_idx]
    avg_scores = [score / len(high_conf_frames) for score in avg_scores]
    #print(avg_scores[0:7])

    cnt = 0
    # Rank classes by averaged score, descending -> take the top three
    ranked_classes = sorted(range(11), key=lambda i: avg_scores[i], reverse=True)
    top_1 = WORDS_COMM[ranked_classes[0]]
    top_2 = WORDS_COMM[ranked_classes[1]]
    top_3 = WORDS_COMM[ranked_classes[2]]

    for i in range(len(avg_scores)):
        if avg_scores[i] < 0:
            avg_scores[i] = -128
            cnt += 1
    if cnt == len(avg_scores):
        top_1 = "Bleh"

    return top_1, top_2, top_3, len(high_conf_frames)


# --- Thread listening for the Enter key, to stop the continuous loop ---
stop_event = threading.Event()


def wait_for_stop_key():
    input()  # blocks until Enter is pressed
    stop_event.set()


listener_thread = threading.Thread(target=wait_for_stop_key, daemon=True)
listener_thread.start()

print("\n=======================================================")
print(" KWS Continuous Mode (reset after prediction) - microphone audio (no file playback)")
print(" Press Enter to stop.")
print("=======================================================\n")

# --- Main continuous loop ---
# Reset and arming of the pipeline are done once at startup - after that the FPGA
# stays armed the whole time and in the loop we only read the next batches of frames
reset_pipeline()
arm_pipeline()

iteration = 0
try:
    while not stop_event.is_set():

        dp.UpdateWireOuts()
        fifo_cnt = dp.GetWireOutValue(0x20)
        if (fifo_cnt >= NUM_FRAMES):
            # print(fifo_cnt)
            frames = read_frame_batch(int(fifo_cnt/4))
            result = classify_batch(frames)

            if DEBUG:
                high_conf = sum(1 for f in frames if f["confidence"] > CONFIDENCE_THRESHOLD)
                max_conf = max((f["confidence"] for f in frames), default=0)
                print(f"[DBG {iteration}] fifo_cnt={fifo_cnt} frames={len(frames)} "
                      f"conf>{CONFIDENCE_THRESHOLD}: {high_conf} max_conf={max_conf}")

            if result is not None:
                top_1, top_2, top_3, valid_count = result

                if (top_1 != "Bleh"):
                    print(f"[{iteration}] TOP1: {top_1:<8} | TOP2: {top_2:<8} | TOP3: {top_3:<8} "
                          f"(reliable frames: {valid_count}/{len(frames)})")

                # Prediction arrived - reload the bitstream and reset before continuing
                reload_and_reset()

            iteration += 1
            # if (iteration % 10 == 0):
            #     disarm_pipeline()
            #     reset_pipeline()
            #     arm_pipeline()
            if (iteration % 100 == 0):
                exit()
finally:
    # Cleanup: disarm the pipeline when the program shuts down
    disarm_pipeline()
    print("\nContinuous mode stopped.")